baseurl                    = "/"
languageCode               = "en-us"
title                      = "Anthony Seure"
pygmentsStyle              = "friendly"
pygmentsCodeFences         = true
footnoteReturnLinkContents = "↩"
